### ISSUE TITLE
sklearn metrics error

### ISSUE THREAD

**Issue by rajae-Bens** [MageshDominator/Blog_References#1]
Hi,
Thank u for this great tutorial
I tried to apply some of these methods on my own datasets but I got an error when trying to calculate the metrics

ValueError: multiclass-multioutput is not supported

I tried the models u used such as K-nearest Neighbor, Decision Trees...

I checked the format of the test labels and predictions and they are encoded in the same way as yours  ex:

[[0 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 0 ... 10 0]
...
[0 0 0 ... 0 0 0]
[0 1 0 ... 0 1 0]
[0 1 0 ... 10 0]]

Any ideas plz

Thank u

**Comment by magesh-technovator** [comment]
Can you verify that all your test labels and predictions labels are binary?
![MultiLabelIssue](https://user-images.githubusercontent.com/33796899/95697572-cebdc580-0c5c-11eb-8612-1e07a132b211.png)
It should like the above one

And also please add a screenshot/traceback of the exception

**Comment by rajae-Bens** [comment]
Hi,

here is my labels format

![Screen Shot 2020-10-12 at 9 25 52 AM](https://user-images.githubusercontent.com/58187895/95723646-45fb5580-0c6d-11eb-8e8a-95b960cc6af9.png)

and the predictions
![Screen Shot 2020-10-12 at 9 30 07 AM](https://user-images.githubusercontent.com/58187895/95723906-97a3e000-0c6d-11eb-9669-11686d27ae09.png)

and here is the error I got

![Screen Shot 2020-10-12 at 9 30 57 AM](https://user-images.githubusercontent.com/58187895/95723970-ad190a00-0c6d-11eb-9ff1-0e21331e410b.png)

Thanks for ur help

**Comment by magesh-technovator** [comment]
Reference from sklearn:
ValueError("Classification metrics can't handle a mix of {0} "
                         "and {1} targets".format(type_true, type_pred))

I think your prediction results are in multiclass-multioutput type, you can verify it here(https://github.com/scikit-learn/scikit-learn/blob/e6555decf8a72958d26d499deb17aabca41a562a/sklearn/utils/multiclass.py#L175)

And one more thing, Your model seems to output "0" for all classes those 5 samples, Can you please verify the predictions once?

And also check the step where you've transformed your output labels to fit for multi-label problem, something like this:
```
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
test_labels = mlb.transform(test_categories)
```

**Comment by rajae-Bens** [comment]
Hi,

Thank s for ur answer. Actually, I solved the problem by modifying the format of my data, and then I used MultiLabelBinarizer to transform them into a convenient format. Now all the metrics are calculated correctly.
However, I have another question plz, I've read that when handling a multi-label classification problem, f1-score is more significant as an evaluation metric do u agree? also, I am getting a very good f1 micro score but the macro score is not that good with a difference of 3x%  do u have an explanation for that? 

thank s for ur help

**Comment by magesh-technovator** [comment]
Thanks for the response.

Regarding micro vs macro, it actually depends on your business needs,

Micro averaging takes into account the proportion for each class, but macro-averaging averages f1-score(or any metric) for all classes treating them equally.
 
If you have an imbalanced dataset(this is typical in real-world scenarios), micro-average is preferable.

And one more suggestion, if you have an imbalanced dataset, based on your business problem figure out the cost of mis-prediction and do some manual error analysis to get insights, and choose the model that gives better performance for your business need.

**Example:** Class A being mis-predicted as Class B will have a major impact, but if Class C gets mis-predicted as Class B it can be tolerated.
